// Destination Data
// All destination information is stored here as a JavaScript array of objects.

const destinations = [
    {
        id: 1,
        name: "Paris",
        country: "France",
        continent: "Europe",
        image: "images/paris.jpg",
        description: "The city of lights and love. Paris is famous for its incredible art, amazing food and iconic landmarks. From the Eiffel Tower to cosy little cafes, there is always something to do.",
        description_short: "City of lights, art and romance",
        attractions: ["Eiffel Tower", "The Louvre Museum", "Notre-Dame Cathedral", "Champs-Élysées", "Montmartre District"],
        costs: { budget: 80, mid: 160, luxury: 350 },
        travelType: ["cultural", "relaxation"],
        budgetRange: "high"
    },
    {
        id: 2,
        name: "Bali",
        country: "Indonesia",
        continent: "Asia",
        image: "images/bali.jpg",
        description: "A tropical paradise with gorgeous rice terraces, ancient Hindu temples and vibrant local culture. Bali is perfect for beach relaxation and cultural exploration.",
        description_short: "Tropical temples and rice terraces",
        attractions: ["Ubud Rice Terraces", "Tanah Lot Temple", "Kuta Beach", "Mount Batur Trek", "Sacred Monkey Forest"],
        costs: { budget: 35, mid: 75, luxury: 200 },
        travelType: ["relaxation", "nature", "cultural"],
        budgetRange: "low"
    },
    {
        id: 3,
        name: "Tokyo",
        country: "Japan",
        continent: "Asia",
        image: "images/tokyo.jpg",
        description: "A city where ancient shrines sit next to futuristic skyscrapers. Tokyo offers unmatched food, culture and an energy unlike anywhere on earth.",
        description_short: "Where tradition meets the future",
        attractions: ["Shibuya Crossing", "Senso-ji Temple", "Akihabara District", "Mount Fuji Day Trip", "Shinjuku"],
        costs: { budget: 70, mid: 140, luxury: 300 },
        travelType: ["cultural", "adventure"],
        budgetRange: "medium"
    },
    {
        id: 4,
        name: "New York",
        country: "USA",
        continent: "North America",
        image: "images/newyork.jpg",
        description: "The city that never sleeps. New York is a melting pot of cultures with world-famous landmarks, an incredible food scene and an energy unlike anywhere else.",
        description_short: "The city that never sleeps",
        attractions: ["Central Park", "Times Square", "Statue of Liberty", "Brooklyn Bridge", "The Met Museum"],
        costs: { budget: 100, mid: 200, luxury: 450 },
        travelType: ["cultural", "adventure"],
        budgetRange: "high"
    },
    {
        id: 5,
        name: "Cape Town",
        country: "South Africa",
        continent: "Africa",
        image: "images/cape-town.jpg",
        description: "One of the most beautiful cities in the world. Table Mountain, beaches, wildlife and a fascinating history all in one place.",
        description_short: "Mountains, beaches and wildlife",
        attractions: ["Table Mountain", "Robben Island", "Cape of Good Hope", "Boulders Beach Penguins", "V&A Waterfront"],
        costs: { budget: 40, mid: 90, luxury: 220 },
        travelType: ["adventure", "nature"],
        budgetRange: "low"
    },
    {
        id: 6,
        name: "Sydney",
        country: "Australia",
        continent: "Oceania",
        image: "images/sydney.jpg",
        description: "Golden beaches, a stunning harbour and a laid-back vibe. The Opera House and Bondi Beach are just two of many incredible spots.",
        description_short: "Beaches, harbour and iconic architecture",
        attractions: ["Sydney Opera House", "Bondi Beach", "Harbour Bridge Climb", "Blue Mountains", "Taronga Zoo"],
        costs: { budget: 90, mid: 180, luxury: 380 },
        travelType: ["adventure", "relaxation"],
        budgetRange: "high"
    },
    {
        id: 7,
        name: "Rio de Janeiro",
        country: "Brazil",
        continent: "South America",
        image: "images/rio.jpg",
        description: "The Marvellous City. Rio is famous for carnival, samba and jaw-dropping natural scenery including Christ the Redeemer and Copacabana Beach.",
        description_short: "Carnival, samba and stunning scenery",
        attractions: ["Christ the Redeemer", "Copacabana Beach", "Sugarloaf Mountain", "Ipanema", "Santa Teresa"],
        costs: { budget: 45, mid: 100, luxury: 250 },
        travelType: ["cultural", "relaxation", "adventure"],
        budgetRange: "medium"
    },
    {
        id: 8,
        name: "Iceland",
        country: "Iceland",
        continent: "Europe",
        image: "images/iceland.jpg",
        description: "A land of fire and ice with dramatic landscapes. Geysers, volcanoes, glaciers and the Northern Lights all in one extraordinary country.",
        description_short: "Northern Lights and volcanic landscapes",
        attractions: ["Northern Lights", "Blue Lagoon", "Golden Circle Route", "Jökulsárlón Glacier Lagoon", "Skógafoss Waterfall"],
        costs: { budget: 110, mid: 200, luxury: 420 },
        travelType: ["adventure", "nature"],
        budgetRange: "high"
    },
    {
        id: 9,
        name: "Santorini",
        country: "Greece",
        continent: "Europe",
        image: "images/santorini.jpg",
        description: "Famous for white-washed buildings and blue domes. Santorini offers some of the most beautiful sunsets and views in the world.",
        description_short: "Iconic blue domes and Greek sunsets",
        attractions: ["Oia Village Sunset", "Fira Town", "Akrotiri Ruins", "Red Beach", "Caldera Boat Tour"],
        costs: { budget: 75, mid: 160, luxury: 400 },
        travelType: ["relaxation", "cultural"],
        budgetRange: "high"
    },
    {
        id: 10,
        name: "Machu Picchu",
        country: "Peru",
        continent: "South America",
        image: "images/machu-picchu.jpg",
        description: "The ancient Incan citadel high in the Andes Mountains. One of the most iconic archaeological sites in the world.",
        description_short: "Ancient Incan ruins in the Andes",
        attractions: ["Sun Gate", "Intihuatana Stone", "Temple of the Sun", "Inca Trail Hike", "Aguas Calientes"],
        costs: { budget: 50, mid: 110, luxury: 280 },
        travelType: ["adventure", "cultural"],
        budgetRange: "medium"
    },
    {
        id: 11,
        name: "Bangkok",
        country: "Thailand",
        continent: "Asia",
        image: "images/bangkok.jpg",
        description: "Chaotic, exciting and full of life. Bangkok has incredible temples, street food and a nightlife scene that goes until sunrise.",
        description_short: "Temples, street food and nightlife",
        attractions: ["Grand Palace", "Wat Pho Reclining Buddha", "Chatuchak Weekend Market", "Khao San Road", "Chao Phraya River"],
        costs: { budget: 30, mid: 65, luxury: 180 },
        travelType: ["cultural", "adventure"],
        budgetRange: "low"
    },
    {
        id: 12,
        name: "Marrakech",
        country: "Morocco",
        continent: "Africa",
        image: "images/marrakech.jpg",
        description: "A sensory explosion of colours, spices and sounds. The ancient medina and labyrinthine souks feel like stepping into another world.",
        description_short: "Vibrant medina and Moorish palaces",
        attractions: ["Jemaa el-Fnaa Square", "Bahia Palace", "Majorelle Garden", "Medina Souks", "Koutoubia Mosque"],
        costs: { budget: 35, mid: 80, luxury: 200 },
        travelType: ["cultural", "adventure"],
        budgetRange: "low"
    },
    {
        id: 13,
        name: "Maldives",
        country: "Maldives",
        continent: "Asia",
        image: "images/maldives.jpg",
        description: "Crystal-clear turquoise water, white sandy beaches and overwater bungalows. The ultimate switch-off holiday with world-class snorkelling.",
        description_short: "Crystal waters and overwater bungalows",
        attractions: ["Overwater Bungalows", "Coral Reef Snorkelling", "Whale Shark Diving", "Male City Tour", "Private Sandbanks"],
        costs: { budget: 150, mid: 350, luxury: 800 },
        travelType: ["relaxation"],
        budgetRange: "high"
    },
    {
        id: 14,
        name: "Rome",
        country: "Italy",
        continent: "Europe",
        image: "images/rome.jpg",
        description: "The Eternal City. Rome has thousands of years of history, world-class pasta and more museums than you could visit in a lifetime.",
        description_short: "Ancient history and world-class food",
        attractions: ["Colosseum", "Vatican and Sistine Chapel", "Trevi Fountain", "Pantheon", "Roman Forum"],
        costs: { budget: 70, mid: 150, luxury: 350 },
        travelType: ["cultural"],
        budgetRange: "medium"
    },
    {
        id: 15,
        name: "Vancouver",
        country: "Canada",
        continent: "North America",
        image: "images/vancouver.jpg",
        description: "Mountains, ocean and a liveable city all in one. Ski in the morning and walk on the beach in the afternoon.",
        description_short: "Mountains, ocean and outdoor adventures",
        attractions: ["Stanley Park", "Granville Island Market", "Capilano Suspension Bridge", "Whistler Ski Resort", "Gastown District"],
        costs: { budget: 85, mid: 170, luxury: 380 },
        travelType: ["adventure", "nature"],
        budgetRange: "medium"
    }
];